"""Compute the findings from the real CSV and write them into README.md between the FINDINGS markers.
Usage: python scripts/generate_findings.py [--write] [path/to/csv]
Requires: pip install pandas numpy scipy
"""
import pathlib
import re
import sys

import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from app.analytics import insights as ins, metrics as m  # noqa: E402
from app.analytics.cleaning import clean_dataframe  # noqa: E402
from app.analytics.constants import OVERTIME_LABELS  # noqa: E402

args = [a for a in sys.argv[1:] if not a.startswith("--")]
csv = args[0] if args else str(ROOT / "data" / "employee_attrition.csv")
df, _ = clean_dataframe(pd.read_csv(csv, encoding="utf-8-sig"))
k = m.kpis(df)


def table(rows, head):
    out = [f"| {head} | Employees | Left | Attrition rate |", "|---|---:|---:|---:|"]
    out += [f"| {r['label']} | {r['employees']:,} | {r['left']:,} | {r['rate']}% |" for r in rows]
    return "\n".join(out)


res = ins.build_insights(df)
seg = ins.segments(df, top=5)
md = [
    f"**{k['total_employees']:,} employees, {k['employees_left']:,} left → overall attrition rate {k['attrition_rate']}%.**",
    "", table(m.group_rates(df, "department", sort_by_rate=True), "Department"),
    "", table(m.group_rates(df, "job_role", sort_by_rate=True), "Job role"),
    "", table(m.group_rates(df, "over_time", ["Yes", "No"], OVERTIME_LABELS), "Overtime"),
    "", "**Key findings (generated by the app's insight engine):**", "",
]
md += [f"- {i['text']}" for i in res["insights"]]
md += ["", "**Highest-attrition segments (min. 20 employees):**", "",
       "| Segment | Employees | Attrition rate |", "|---|---:|---:|"]
md += [f"| {r['segment']} | {r['employees']} | {r['rate']}% |" for r in seg["rows"]]
md += ["", "_All findings are observed associations, not proof of causation._"]
text = "\n".join(md)

if "--write" in sys.argv:
    readme = ROOT / "README.md"
    new = re.sub(r"(<!-- FINDINGS:START -->).*?(<!-- FINDINGS:END -->)", lambda mo: f"{mo.group(1)}\n{text}\n{mo.group(2)}",
                 readme.read_text(encoding="utf-8"), flags=re.S)
    readme.write_text(new, encoding="utf-8")
    print("README.md updated")
else:
    print(text)
